name: pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cahce cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-npm-cache-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build REPL
        run: |
          cd frontend && npm install && npm run build

      - name: Build book
        run: |
          cd backend
          chmod u+x example/assets/bin/* && cp example/assets/bin/* /usr/local/bin
          cargo build --release && mdbook build example

      - name: Merge build assets
        run: |
          mv backend/example/book build
          mv frontend/dist build/embed

      - name: Deploy to github pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
